### ISSUE TITLE
Main form layout problems on higher DPI

### ISSUE THREAD

**Issue by atifaziz** [toehead2001/aeroshot#15]
AeroShot 1.3.2 did not layout correctly on higher DPI, like at 120 shown below, and made it difficult to use if you needed to tweak the settings:

![AeroShot 1.3.2](https://cloud.githubusercontent.com/assets/20511/8775949/6e6c6648-2eed-11e5-9157-819f806259ed.png)

[AeroShot  Mini v1.4](https://github.com/toehead2001/aeroshot/releases/tag/v1.4.0) continues to suffer from the same issue:

![AeroShot  Mini v1.4.0](https://cloud.githubusercontent.com/assets/20511/8775934/50146dbc-2eed-11e5-90b1-06c8e180453d.png)

I can submit a fix that will scale the layout at 96, 120 or any other DPI:

![AeroShot  Mini v1.4.0 (fixed)](https://cloud.githubusercontent.com/assets/20511/8776082/b826c098-2eee-11e5-94a4-f1daf889dfd1.png)

**Comment by toehead2001** [comment]
Thank you for contributing again! I'm glad you were able to find my fork here on Github. :smile:
