### ISSUE TITLE
Convert tabs to spaces

### ISSUE THREAD

**Issue by atifaziz** [toehead2001/aeroshot#18]
I absolutely hate to bring up this discussion but I'd like to still try my luck anyway and make a plea for the case that while tabs work fine in code editors and everyone can go about their usual business & preferences, code is also read online a lot today (here via the GitHub web UI). Browsers don't accommodate preferences of tab widths and therefore tabs hinder online reading with “white noise.”

Again, I don't want this to degenerate into any sort of carnage so I'll suck it up & accept if you close this as “I don't care” or “won't fix” for now. :smile:

**Comment by toehead2001** [comment]
Resolved in 048055a26a993726aaf3ad7cebf84ea9e003a607
