### ISSUE TITLE
Upgrade to Visual Studio 2015

### ISSUE THREAD

**Issue by atifaziz** [toehead2001/aeroshot#25]
AeroShot solution and project originates from VS 2010. Now that [VS 2015 is out](http://blogs.msdn.com/b/somasegar/archive/2015/07/20/visual-studio-2015-and-net-4-6-available-for-download.aspx), any objections to upgrading it considering that it still supports targeting .NET Framework 2.0? This would be primarily to use C# 6. It's a small code base and tool so worth the fun. :)

**Comment by toehead2001** [comment]
I am running VS 2015, but I have not looked into C# 6 yet. Will using C# 6 require the end-user to have the .Net 4.6 installed? or will VS compile it to IL that can be run by some older versions of the framework?

**Comment by atifaziz** [comment]
Most things in C# 6 are syntax sugar like many versions before it. And as I said earlier, you can use C# 6 features, target earlier versions of the .NET Framework like 2.0 and the compiled IL and metadata will be understood by that runtime just fine. The end-user won't need .NET 4.6 from the end-user and if it did then I wouldn't be suggesting the upgrade.

**Comment by toehead2001** [comment]
Thanks for confirming that. Go ahead and open a pull request for this.

**Comment by atifaziz** [comment]
Sweet. :+1:

BTW, I'll have to force the upgrade. Technically, VS 2015 won't upgrade the solution and project by just opening it up in the IDE. However, using C# 6 syntax and leaving VS in 2010 format could be misleading as it won't compile on earlier versions of VS. Anyway, I'm not in a hurry for this. I'd rather close #19 and #26 done first.

**Comment by toehead2001** [comment]
Resolved in a7b6455f254916c42fc4e2963270203474151b9b
