### ISSUE TITLE
Integrate into PowerToys?

### ISSUE THREAD

**Issue by zDaleZ** [toehead2001/aeroshot#30]
Hello, thank you for developing this tool, it's convenient to shoot pretty screenshots.
But I also noticed it stopped maintaining for a long time, so is that a good idea to integrate it into PowerToys? I think so, so I've [opened an issue there](https://github.com/microsoft/PowerToys/issues/29353). This software can keep maintaining and be better after integrating.

Do you think so? However, there's a bit of a hurdle, so I hope you can take a little time to have a look and provide some help. Thanks a lot!

**Comment by toehead2001** [comment]
I don't really see the point of that.

Since Windows doesn't use Aero Glass borders anymore, there's really little reason to use this utility.

**Comment by zDaleZ** [comment]
Well, you know, screenshots with the shadows and the clean corners are prettier, although there're no glass borders.
I can't describe how better and meaningful the screenshots shot by this tool is, I used to believe that Windows never can't shoot screenshots as pretty as macOS until found your software (... 's fork). I do hope this software can be alive and one of the way is that.

By the way, [WinSnap](https://www.ntwind.com/software/winsnap.html) has the same ability and not free. Since that have the reason to exist, yours have more reasons.
***
So if you think no problem with this, please tell Microsoft that they can fork your source code. It seems presently they need your permission to continue considering.

**Comment by zDaleZ** [comment]
Hello? I really wonder your idea. Please just reply with your final decision and then you can close this issue. Thanks!

**Comment by toehead2001** [comment]
Hi, sorry I missed your previous comments.
The code is using a libre license, so I don't see why anyone would be asking for explicit permission beyond that.

**Comment by zDaleZ** [comment]
> The code is using a libre license, so I don't see why anyone would be asking for explicit permission beyond that.

That's Microsoft — whether the license is libre or not (even MIT), but I don't know if they are for this reason this time.
