### ISSUE TITLE
Delayed screenshot

### ISSUE THREAD

**Issue by GoogleCodeExporter** [toehead2001/aeroshot#9]
```
1. Open a drop-down menu or a hidden menu with Alt (Explorer.exe, Firefox…). 
Something volatile to losing focus.
2. Try to capture window with AeroShot.
* Using the GUI makes the subject lose focus and hide before the screenshot is 
taken.
* The Alt in Alt-PrintScreen also hides my subjects.

Using AeroShot 1.3.2 on Windows 7 Home Premium.

I would like to be able to shoot these elusive targets and I suspect adding a 
option to delay the actual screenshot from the time of the 
key-press/button-click by a couple of seconds would allow it as follows:

Activate AeroShot -> Open and focus subject -> AeroShot fires

```

Original issue reported on code.google.com by `syntaxer...@gmail.com` on 28 Nov 2012 at 1:31

**Comment by toehead2001** [comment]
**There are now there options for the Hotkeys:**
*Alt+PrtSc* = immediate; no delay
*Alt+PrtSc* (delay option enabled) = Delay of 1 - 10 seconds
*Ctrl+Alt+PrtSc* = hard coded delay of 3 seconds

The third option is there for my preference. 99% of time I won't need a delay. When I do, I don't want to have to toggle the option to turn it on, and 3 seconds is the perfect amount of time for me.

**Comment by atifaziz** [comment]
@toehead2001 Thanks for applying my patch :+1: and I'm glad to see you left the hard-coded option in because as you said and as I've found too, it's good enough for the 99% case.
